---
 - name: Config Elk VM with Docker
   hosts: elk
   remote_user: azadmin
   become: true
   tasks:

   - name: VM Max
     command: sysctl -w vm.max_map_count=262144

   - name: Install docker.io
     apt:
        force_apt_get: yes
        update_cache: yes
        name: docker.io
        state: present

   - name: Install pip3
     apt:
        force_apt_get: yes
        name: python3-pip
        state: present

   - name: Install Docker python module
     pip:
        name: docker
        state: present

   - name: Download and launch docker elk
     docker_container:
       name: elk-docker
       image: sebp/elk:761
       state: started
       restart_policy: always
       published_ports:
         - 5601:5601
         - 9200:9200
         - 5044:5044

   - name: Enable Docker service on boot
     systemd:
       name: docker
       enabled: yes
