---
  - name: Config Web VM with Docker
    hosts: webservers
    become: true
    tasks:

    - name: docker.io
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: apache2 remove
      apt:
       name: apache2
       state: absent
 
    - name: Install pip3
      apt:
       name: python3-pip
       state: present

    - name: Install Docker Python Module (state=present is not optional)
      pip:
       name: docker
       state: present

    - name: download and launch a docker web container
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        restart_policy: always
        published_ports: 80:80


  - name: Config Elk VM with Docker
    hosts: elk
    remote_user: azadmin
    become: true
    tasks:
  
    - name: VM Max
      command: sysctl -w vm.max_map_count=262144

    - name: Use more memory
      sysctl:
       name: vm.max_map_count
       value: '262144'
       state: present
       reload: true

    - name: Install docker.io
      apt:
         force_apt_get: yes
         update_cache: yes
         name: docker.io
         state: present

    - name: Install pip3
      apt:
         force_apt_get: yes
         name: python3-pip
         state: present

    - name: Install Docker python module
      pip:
         name: docker
         state: present

    - name: Download and launch docker elk
      docker_container:
        name: elk-docker
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044

    - name: Enable Docker service on boot
      systemd:
        name: docker
        enabled: yes
